CUDA: Try to link dl if NVTX v3 check failed
AOCC requires having all names being linked when building an application,
due to the added flag `--no-allow-shlib-undefined`. When not adding "-ldl"
to the linker line, detecting NVTX v3 will fail with the following error
message:

ld.lld: error: ./.libs/libconftest.so: undefined reference to dlopen
[--no-allow-shlib-undefined]
ld.lld: error: ./.libs/libconftest.so: undefined reference to dlsym
[--no-allow-shlib-undefined]
ld.lld: error: ./.libs/libconftest.so: undefined reference to dlclose
[--no-allow-shlib-undefined]
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Therefore, try to add "-ldl" to the ldflags if detection failed.

Signed-off-by: Jan André Reuter <j.reuter@fz-juelich.de>