libwrap-test: Ensure files get regenerated
On some system, changing prerequisites (libwrap.h, main.c, Makefile,
*.filter) might not cause regeneration of targets (libwrap.i,
foo.wrap, ...) due to timestamp resolution issues. To force a
regeneration, run `make clean all`.

The error that infrequently showed up:
```
ERROR: Cannot find any function to wrap. Make sure to add include
statements to libwrap.h, and verify that the filter does not filter
out everything.
```