build: Allow for succesful builds on Fugaku
On Fugaku's compute nodes with `SCOREP_COMPILER_FC_FUJITSU` and
`SCOREP_COMPILER_CC_FUJITSU` or `SCOREP_COMPILER_CC_CLANG`, i.e.,
`fcc|FCC|frt|mpifcc|mpiFCC|mpifrt` or
`fcc -Nclang|FCC -Nclang|frt|mpifcc -Nclang|mpiFCC -Nclang|mpifrt`,
static builds succeed if `FLIBS` are omitted. Internal otf2, cubew,
and cubelib were used.

There was no luck with shared builds. `installcheck` bails out when
linking `jacobi-mpi-cc_default`, the first MPI instrumentercheck.

The traditional `fcc` build fails with:
```
/usr/bin/ld: /vol0003/rccs-sdt/data/a01039/install-perftools-fcc-traditional-rpath-shared/pertools-installation.tmp/scorep/_build_fcc-fujitsu-mpi/build-backend/../installcheck/instrumenter_checks/bin/jacobi-mpi-cc_default: hidden symbol `stat' in /usr/lib64/libc_nonshared.a(stat.oS) is referenced by DSO
/usr/bin/ld: final link failed: Bad value
```

The `-Nclang` fails with:
```
/data/rccs-sdt/a01039/opt/perftools/scorep/116-rpath/aarch64/fcc-clang-fujitsu-mpi-rpath-shared-patched/lib/libscorep_measurement.so: undefined reference to `_ULaarch64_init_local2'
/data/rccs-sdt/a01039/opt/perftools/scorep/116-rpath/aarch64/fcc-clang-fujitsu-mpi-rpath-shared-patched/lib/libscorep_adapter_mpi_event.so: undefined reference to `abort_'
/data/rccs-sdt/a01039/opt/perftools/scorep/116-rpath/aarch64/fcc-clang-fujitsu-mpi-rpath-shared-patched/lib/libscorep_adapter_mpi_event.so: undefined reference to `__jwe_ilst'
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```